apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externaldnsrecords.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dnsName:
                  type: string
                recordType:
                  type: string
                values:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: externaldnsrecords
    singular: externaldnsrecord
    kind: ExternalDNSRecord
    shortNames:
      - ednsr

